### ISSUE TITLE
Read.me 

### ISSUE THREAD

**Issue by Tardionm** [PhPv/Energy.MLA#1]
Цель проекта
Увеличить выручку от продажи электроэнергии

В зависимости от погодных условий изменяется потенциально возможная выработка электроэнергии и ее генерация солнечными панелями и ветряками. Мы обучаем модели, которые используют данные архивов выработки за 1-2 года с дискретностью в час и обучаем модель, которая на основе данных с предыдущих периодов позволить спрогнозировать возможную выработку за будущие периоды

Проект позволяет просмотреть данные анализа в веб-интерфейсе, будет бесплатным в рамках тестового периода, а также легко масштабируется. Полученные данные позволят накопить необходимые запасы энергии в хранилищах во время наиболее благоприятных периодов и использовать их в менее благоприятные периоды для выработки «не теряя» производительность на протяжении всего времени работы.

**Comment by PhPv** [comment]
cool
